[project]
name = "inecosysllm"
version = "0.3.9"
description = "LMbacked service to help boost Inecosys marketing in early stages of the company"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "flask>=3.1.1",
]
